import AppKit
import XCTest
@testable import papuga

final class ClipboardHistoryPersistenceTests: XCTestCase {
    private var tempDirectory: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        tempDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent("papuga-clipboard-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: tempDirectory, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        if let tempDirectory {
            try? FileManager.default.removeItem(at: tempDirectory)
        }
        try super.tearDownWithError()
    }

    func test_refreshPersistsClipboardEntryAndBootstrapLoadsIt() {
        let originalClipboard = ClipboardManager().save()
        defer { ClipboardManager().restore(originalClipboard) }

        let fileURL = tempDirectory.appendingPathComponent("clipboard-history.jsonl")
        let manager = ClipboardHistoryManager(maxEntries: 10, pollInterval: 60, fileURL: fileURL)
        waitForBootstrap(manager)

        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString("persistent copy", forType: .string)

        manager.refreshNow()
        XCTAssertTrue(waitForFile(at: fileURL))
        manager.stopMonitoring()

        let reloaded = ClipboardHistoryManager(maxEntries: 10, pollInterval: 60, fileURL: fileURL)
        waitForBootstrap(reloaded)

        XCTAssertEqual(reloaded.entries.count, 1)
        XCTAssertEqual(reloaded.entries.first?.title, "Текст")
        XCTAssertEqual(reloaded.entries.first?.subtitle, "persistent copy")
        XCTAssertEqual(reloaded.entries.first?.state.items.first?.data[.string].flatMap {
            String(data: $0, encoding: .utf8)
        }, "persistent copy")
    }

    func test_refreshSkipsConfidentialAndTransientClipboardItems() {
        let originalClipboard = ClipboardManager().save()
        defer { ClipboardManager().restore(originalClipboard) }

        let excludedTypes = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword"
        ]

        for typeName in excludedTypes {
            let fileURL = tempDirectory.appendingPathComponent("\(typeName).jsonl")
            let manager = ClipboardHistoryManager(maxEntries: 10, pollInterval: 60, fileURL: fileURL)
            waitForBootstrap(manager)

            let item = NSPasteboardItem()
            item.setString("secret sentinel", forType: .string)
            item.setData(Data(), forType: NSPasteboard.PasteboardType(typeName))
            NSPasteboard.general.clearContents()
            XCTAssertTrue(NSPasteboard.general.writeObjects([item]))

            manager.refreshNow()
            RunLoop.current.run(until: Date().addingTimeInterval(0.1))
            manager.stopMonitoring()

            XCTAssertTrue(manager.entries.isEmpty, typeName)
            XCTAssertFalse(FileManager.default.fileExists(atPath: fileURL.path), typeName)

            let reloaded = ClipboardHistoryManager(maxEntries: 10, pollInterval: 60, fileURL: fileURL)
            waitForBootstrap(reloaded)
            XCTAssertTrue(reloaded.entries.isEmpty, typeName)
        }
    }

    func test_saveWithExcludedTypeDoesNotReadClipboardRepresentations() {
        let originalClipboard = ClipboardManager().save()
        defer { ClipboardManager().restore(originalClipboard) }
        let marker = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let provider = TrackingPasteboardDataProvider()
        let item = NSPasteboardItem()
        item.setDataProvider(provider, forTypes: [.string])
        item.setData(Data(), forType: marker)
        NSPasteboard.general.clearContents()
        XCTAssertTrue(NSPasteboard.general.writeObjects([item]))
        provider.didProvideData = false

        let state = ClipboardManager().save(excluding: [marker])

        XCTAssertNil(state)
        XCTAssertFalse(provider.didProvideData)
    }

    func test_signatureIsStableForSamePasteboardContent() {
        let state = SavedPasteboardState(
            items: [
                SavedPasteboardState.Item(
                    types: [.string, .html],
                    data: [
                        .string: Data("hello".utf8),
                        .html: Data("<b>hello</b>".utf8)
                    ]
                )
            ],
            changeCount: 1
        )
        let sameContentDifferentOrder = SavedPasteboardState(
            items: [
                SavedPasteboardState.Item(
                    types: [.html, .string],
                    data: [
                        .html: Data("<b>hello</b>".utf8),
                        .string: Data("hello".utf8)
                    ]
                )
            ],
            changeCount: 99
        )

        XCTAssertEqual(
            ClipboardHistorySignature.make(for: state),
            ClipboardHistorySignature.make(for: sameContentDifferentOrder)
        )
    }

    private func waitForBootstrap(_ manager: ClipboardHistoryManager) {
        let expectation = expectation(description: "Clipboard history bootstrap")
        manager.bootstrap {
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 2)
    }

    private func waitForFile(at fileURL: URL) -> Bool {
        let deadline = Date().addingTimeInterval(2)
        while Date() < deadline {
            if FileManager.default.fileExists(atPath: fileURL.path) {
                return true
            }
            RunLoop.current.run(until: Date().addingTimeInterval(0.05))
        }
        return false
    }
}

private final class TrackingPasteboardDataProvider: NSObject, NSPasteboardItemDataProvider {
    var didProvideData = false

    func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        didProvideData = true
        item.setString("secret sentinel", forType: type)
    }
}
